library(tidyverse)
library(stringr)
library(fs)
library(tictoc)
library(future)
library(tidylog)
library(lubridate)
# load("V:/BYH/Datadrevet ledelse/4_R/kopier_insite_data/insite_filer.RData")
map(afd_filer_der_skal_slettes$fuld_sti, file.remove)
map(afd_filer_der_skal_opdateres$fuld_sti, file.remove)
map(afd_filer_der_mangler$fuld_sti, kopier_filer_til_afd, "Y:/")
map(fil_info_æmo$fuld_sti, kopier_æmofiler_til_afd, "Y:/")
map(mappe_afd_der_skal_opdateres$mappe, opdater_mapper)
